### ISSUE TITLE
U - Define requirements criteria that file organization must satisfy

### ISSUE THREAD

**Issue by escattone** [mdn/kuma#6441]
### Acceptance Criteria
- [x] Document, within this issue, a list of criteria that a GitHub file organization would have to satisfy. For example, it would have to support the ability to discover any given document's parents or children.

**Comment by escattone** [comment]
Criteria that a GitHub file organization would have to satisfy:
- Provide the locale, slug, title, and URL of every child in the tree below any given document. The hierarchy is provided via the `parent_topic` foreign key. TODO: Confirm that the slug hierarchy matches the `parent_topic` hierarchy.

**Comment by escattone** [comment]
**These are the 4 documents within the `en-US` locale whose slugs are NOT a sub-path of their parent's slug:**

doc.slug = `SpiderMonkey/GCIntegration`
doc.parent_topic.slug = `Mozilla/Projects/SpiderMonkey`

doc.slug = `Gecko/FAQ`
doc.parent_topic.slug = `Mozilla/Gecko`

doc.slug = `NSS/PKCS_11_Netscape_Trust`
doc.parent_topic.slug = `Mozilla/Projects/NSS`

doc.slug = `Garbage_MixedContentBlocker`
doc.parent_topic.slug = `Security`

**Comment by escattone** [comment]
@peterbe @tobinmori I think the documents whose slug is not a sub-path of their parent's slug (technically, their `parent_topic`'s slug) represent a problem that we need to resolve in some way, because we need some reliable way to define parent-child relationships within our file organization. One way is to explicitly specify the parent slug of every document (in each document's metadata for example). In that case, we wouldn't have to worry about these parent-child slug mismatches. Another way is to fix these mismatches, i.e. make sure every document's slug is a sub-path of its parent's slug, and then we could reliably assume that the slugs define the hierarchy. If I'm not mistaken, I think @peterbe's current file organization is relying on the slugs to define the hierarchy.

There are not many mismatches within the `en-US` locale, but other locales have substantial numbers of them.

**Comment by escattone** [comment]
@chrisdavidmills @wbamberg @Elchi3 It would be awesome to get your thoughts on documents whose slug is not a sub-path of their parent's slug (see https://github.com/mdn/kuma/issues/6441#issuecomment-589402410).

**Comment by peterbe** [comment]
> If I'm not mistaken, I think @peterbe's current file organization is relying on the slugs to define the hierarchy.

peterbe's current file organization only records the slugs and, for the breadcrumb parents, it uses something like:
```javascript
var thisUrl = document.slug.split('/')
var parents = []
while (thisUrl.length) {
    thisUrl.pop()
    parents.push(allTitles[thisUrl.join('/')])
}
```

That is incorrect but you have pinpointed the solution: `parent_topic`!
This is currently NOT incorporated in the yari mysql importer. But would be easy to add. I can take care of that. 

As a matter of fact, can you review this recently added code comment?
https://github.com/mdn/stumptown-renderer/commit/f9f97add96937b67989e56acd86cb7271c76a5bf

The next piece of work might be to verify that ALL `document.parent_topic` relationships are better. I.e. better that relying on `/` splitting the slug to get to parents.

**Comment by peterbe** [comment]
Note, Yari currently uses the `Document.parent` which gets used to define the `other_translations`. E.g.

```yaml
title: '<video>: The Video Embed element'
slug: Web/HTML/Element/video
locale: en-US
other_translations:
  - slug: Web/HTML/Element/video
    locale: ca
  - slug: Web/HTML/Element/video
    locale: de
  - slug: Web/HTML/Elemento/video
    locale: es
  - slug: Web/HTML/Element/video
    locale: fr
  - slug: Web/HTML/Element/video
    locale: ja
  - slug: Web/HTML/Element/Video
    locale: ko
  - slug: Web/HTML/Element/video
    locale: pl
  - slug: Web/HTML/Element/Video
    locale: pt-BR
  - slug: Web/HTML/Elemento/Video
    locale: pt-PT
  - slug: Web/HTML/Element/video
    locale: ru
  - slug: Web/HTML/Елемент/video
    locale: uk
  - slug: Web/HTML/Element/video
    locale: zh-CN
```

Actually, most of the time the en-US version doesn't have a `parent` so when you see `other_translations` in an English document, it's actually computed by collecting the "reverse" parent pointers. 

Sanity check:

```
>>> d = Document.objects.get(locale='en-US', slug='Web/HTML/Element/video')
>>> assert not d.parent
>>> d.parent_topic
<Document: /en-US/docs/Web/HTML/Element (HTML elements reference)>
>>>
>>> pt = Document.objects.get(locale='pt-PT', slug='Web/HTML/Elemento/Video')
>>> pt.parent
<Document: /en-US/docs/Web/HTML/Element/video (<video>: The Video Embed element)>
>>> pt.parent_topic
<Document: /pt-PT/docs/Web/HTML/Elemento (Referência dos elementos HTML)>
>>>
```
